name: Scrape Bowtie

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3,23,43 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest data
        run: |-
          parallel curl -O 'https://bowtie.report/draft{}.json' ::: 3 4 6 7 2019-09 2020-12

      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest report: ${timestamp}" || exit 0
          git push
